### ISSUE TITLE
request (?): to use argocd-helmfile with argoc-image-updater

### ISSUE THREAD

**Issue by dmitriyr333** [travisghansen/argo-cd-helmfile#12]
hello, I would like to ask if it's possible to use your scripts for argocd+helmfile with [argocd-image-updater](https://github.com/argoproj-labs/argocd-image-updater)

as of right now, I was not able to make this work due to the fact that argocd-image-updater **does not** recognize [Plugins](https://github.com/argoproj-labs/argocd-image-updater/issues/168)

could you perhaps think of any way "fooling" image-updater into believing it's a plain'old Helm file? Afterall, it only needs to update image.tag 

thank you

**Comment by travisghansen** [comment]
I don’t use that but the chances seem slim if it doesn’t support plugins. If a way is possible I’m open to changes that could be made however.

**Comment by dmitriyr333** [comment]
Understood. 
I'll close this issue as it seems it is out of scope for this particular project.
