### ISSUE TITLE
[Inquiry/ question ] Does this plugin support complex helmfile structure .. 

### ISSUE THREAD

**Issue by Coder63** [travisghansen/argo-cd-helmfile#15]
We have little complex helmfile structure with dependencies , files, templates & multiple charts and the structure looks like below 

When I;m trying to add one of the chart .. I see redis error but I feel this is the effect not the cause. Any help will be appreciated . thanks 

Error: 
`Unable to save changes: application spec for app1 is invalid: InvalidSpecError: Unable to generate manifests in helmfile.d: rpc error: code = Unknown desc = dial tcp: lookup argocd-redis on 172.18.0.10:53: no such host`

ArgoCD manifest 
`project: default
source:
  repoURL: 'https://my repo'
  path: helmfile.d/
  targetRevision: my branch
  plugin:
    name: helmfile
    env:
      - name: HELMFILE_GLOBAL_OPTIONS
        value: '--environment region1 --file helmfile.d/helmfile.yaml --selector name=app1'
destination:
  server: 'https://kubernetes.default.svc'
  namespace: be
syncPolicy: {}`

 ![image](https://user-images.githubusercontent.com/22849289/175112695-c4cc1963-765c-4183-8bcd-f5be14b4acda.jpeg)

**Comment by Coder63** [comment]
![Uploading Screen Shot 2022-06-22 at 11.15.17 AM.png…]()

**Comment by abrarcv170** [comment]
@Coder63  is this issue resolved? ,iam still getting the same issue.
