### ISSUE TITLE
Argocd Helmfile plugin should detect changes when refresh or resync from the repository

### ISSUE THREAD

**Issue by reddymh** [travisghansen/argo-cd-helmfile#19]
Argocd Helmfile plugin should detect changes when refresh or resync from the repository when  we change the templates.
Currently its not detecting the change and even if  we re-deploy the application the old manifests are cached somewhere.

**Comment by travisghansen** [comment]
Hmm, never ran into an issue like that. What version of argocd are you running? Can you give further details about how everything is structured on your end?

**Comment by reddymh** [comment]
@travisghansen  below are the details:

Argocd VersionL: 2.2.5

helmfile:

---
repositories:
  - name: helm-repo
    url: <REPO_URL>/artifactory/helm-repo
    oci: false

helmDefaults:
  createNamespace: false
  timeout: 900

releases:
  - name: testapp1
    chart: helm-repo/app1
    namespace: app1
    force: true
    createNamespace: true
    version: 0.14.0
    values:
      - ./values/dev/app1-values.yaml

  - name: testapp2
    chart: helm-repo/app2
    namespace: app2
    force: true
    createNamespace: true
    version: 1.13.0

**Comment by travisghansen** [comment]
Do you update the chart version in the repo when updating templates?

Do you update chart version in helmfile after updates have been published?
