### ISSUE TITLE
application spec for testapp is invalid: InvalidSpecError: Unable to generate manifests

### ISSUE THREAD

**Issue by abrarcv170** [travisghansen/argo-cd-helmfile#25]
Unable to save changes: application spec for testapp is invalid: InvalidSpecError: Unable to generate manifests in new/: rpc error: code = Unknown desc = `argo-cd-helmfile.sh init` failed exit status 1:

**Comment by travisghansen** [comment]
I’ll need more info. Can you send over the deployment and also the application yaml you’re attempting to use?

**Comment by abrarcv170** [comment]
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testapp
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/abrarcv170/helmfiletest.git
    #targetRevision: main
    path: new/
    plugin:
      env:
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --file new/helmfile.yaml  
      name: helmfile

**Comment by abrarcv170** [comment]
https://github.com/abrarcv170/helmfiletest.git ,this is  a public repo you can check the helmfile .

**Comment by abrarcv170** [comment]
kubeVersionOverride: "1.16.15"
repoServer:
  initContainers:
  - name: download-tools
    image: alpine:3.8
    command: [sh, -c]
    args:
      - wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/travisghansen/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&
        chmod +x /custom-tools/argo-cd-helmfile.sh &&
        wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.138.7/helmfile_linux_amd64 &&
        chmod +x /custom-tools/helmfile
    volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
  - mountPath: /usr/local/bin/argo-cd-helmfile.sh
    name: custom-tools
    subPath: argo-cd-helmfile.sh
  - mountPath: /usr/local/bin/helmfile
    name: custom-tools
    subPath: helmfile
  volumes:
  - name: custom-tools
    emptyDir: {}


this is the helm value file of argocd

**Comment by travisghansen** [comment]
ok, and in the server config you'll need something like this:

```
    configManagementPlugins: |
      - name: helmfile
        init:                          # Optional command to initialize application source directory
          command: ["argo-cd-helmfile.sh"]
          args: ["init"]
        generate:                      # Command to generate manifests YAML
          command: ["argo-cd-helmfile.sh"]
          args: ["generate"]
```

do you have that?

**Comment by abrarcv170** [comment]
yes i  have .
