### ISSUE TITLE
kubectl rollout restart interrupted ?

### ISSUE THREAD

**Issue by kfirfer** [travisghansen/argo-cd-helmfile#31]
hello

This is only an estimation, but I guess argocd  with selfheal turned on, is interrupting manual rollout restart

when I trying to rollout the deployment, the newly created pods gets terminating after 20-40 seconds

when I do the same thing on deployment that doesnt managed by argo, I dont get the interruption

Don’t know if it’s the plugin, argo itself, or completely other think

**Comment by travisghansen** [comment]
Seems likely unrelated. argocd simply invokes kubectl apply behind the scenes.

**Comment by kfirfer** [comment]
hi @travisghansen 

when we issue :
```
kubectl rollout restart deploy agent
```

What he does under the hood is adding annotation name:
`kubectl.kubernetes.io/restartedAt`

I guess what he does is:
When I dont use helmfile plugin, argocd selfheal have mechanism to ignore this annotation when he trying to auto-sync git repository by selfheal

But in the plugin , argocd doesn't go through git and matching the annotations, he just apply everything he got templated from helmfile plugin

![Screenshot 2022-12-17 at 16 42 59](https://user-images.githubusercontent.com/7741545/208247810-f60ade65-f8c2-4300-926c-f31cc765615e.png)

**Comment by kfirfer** [comment]
Im still investigate it, mabye im wrong
But its seems like the plugin doesnt wait for the rollout to finish

**Comment by kfirfer** [comment]
@travisghansen My mistake
its doesnt related to the plugin at all

argocd doesnt know to handle empty annotations while rollout
hence, its chart problem
