### ISSUE TITLE
Mask helm repository password in ArgoCD UI

### ISSUE THREAD

**Issue by kfirfer** [travisghansen/argo-cd-helmfile#32]
Hello

When some helm repository uses password, and he gets "context deadline exceeded" while fetching the chart(s), he showing the full helmfile command without masking the helm repository password in ArgoCD UI

For example:

```
rpc error: code = Unknown desc = `argo-cd-helmfile.sh init` failed exit status 1: v3.8.1+g5cb9af4 helmfile version 0.148.1 starting init Adding repo elastic https://harbor.example.com/chartrepo/elastic in ./helmfile.yaml: command "/usr/local/bin/helm" exited with non-zero status: PATH: /usr/local/bin/helm ARGS: 0: /usr/local/bin/helm (19 bytes) 1: repo (4 bytes) 2: add (3 bytes) 3: elastic (7 bytes) 4: https://harbor.example.com/chartrepo/elastic (43 bytes) 5: --force-update (14 bytes) 6: --username (10 bytes) 7: admin (5 bytes) 8: --password (10 bytes) 9: thispasswordisnotmasked (16 bytes) ERROR: exit status 1 EXIT STATUS 1 STDERR: Error: context deadline exceeded COMBINED OUTPUT: Error: context deadline exceeded
```

Set `thispasswordisnotmasked ` as the password

**Comment by travisghansen** [comment]
Finally have some time to work on this project. I'm not sure what can be done about this honestly. Another option may be to set that param via env var. I'll keep this on the radar this week as I look into updating this project to the sidecar approach.

**Comment by travisghansen** [comment]
You can set the username/password as ENV vars: https://helmfile.readthedocs.io/en/latest/#configuration
