### ISSUE TITLE
Helmfile is moved

### ISSUE THREAD

**Issue by vadim-a-nesterov** [travisghansen/argo-cd-helmfile#34]
The official repo of helmfile https://github.com/roboll/helmfile is moved https://github.com/helmfile/helmfile

**Comment by travisghansen** [comment]
Thanks for the heads up, I'll update any references over the next few days as I work on this project.

**Comment by travisghansen** [comment]
Fixed here: https://github.com/travisghansen/argo-cd-helmfile/commit/acd5d530991e81a2488083a860ce8ada575da99b
