### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by elemental-lf** [travisghansen/argo-cd-helmfile#4]
Hi there!

I've got an as of yet private repository which is based on https://github.com/chatwork/dockerfiles/tree/master/argocd-helmfile but also includes a simplified version of your `argo-cd-helmfile.sh` script. The repository by Chatwork is MIT licensed. Could you please clearify on the license of your repository? Licensing it under MIT would be most straightforward in my case but any MIT compatible license would help. Thanks!

**Comment by travisghansen** [comment]
MIT is what I would use for this project yes. I’ll add and commit.

**Comment by travisghansen** [comment]
Done.
