### ISSUE TITLE
Setting --skip-deps as optional

### ISSUE THREAD

**Issue by atefhaloui** [travisghansen/argo-cd-helmfile#52]
Hi,
    Would it be possible to set `--skip-deps` flag as optional when calling `template` command ?
My workaround actually is to point `HELMFILE_INIT_SCRIPT_FILE` to a simple shell script:
```shell
#!/bin/sh

HELM_BINARY="helm-v3"
helm="$(which ${HELM_BINARY})"

${helm} repo update
${helm} dependency buid
```

Thank you

**Comment by travisghansen** [comment]
Are you using oci charts or something that requires doing this? Deps otherwise should be gathered in the init phase.

**Comment by atefhaloui** [comment]
> Are you using oci charts or something that requires doing this? Deps otherwise should be gathered in the init phase.

I'm just using a homemade repo without any oci. I was trying to avoid the init step but it's clear that it's a required step in my case in order to add bitnami/common repo and build the dependencies.

Thank you very much for your help.
