### ISSUE TITLE
[Feature] Allow to use helmfile.yaml.gotmpl

### ISSUE THREAD

**Issue by sule26** [travisghansen/argo-cd-helmfile#65]
Instead of just accept `helmfile.d` and `helmfile.yaml`, it would be great if it starts to accept `helmfile.yaml.gotmpl` as well.

**Comment by sule26** [comment]
https://github.com/travisghansen/argo-cd-helmfile/pull/66

**Comment by sule26** [comment]
Resolves #66

**Comment by NathanFirmo** [comment]
Have u created an issue that resolves a pull request? Do you know git, bro?

![2024-10-01_18-45](https://github.com/user-attachments/assets/97378d91-e713-41a5-85bd-517e122fdd60)
